FROM alpine:3

LABEL author="Gerson Wissaluno"
LABEL company="Programer Zaman Now" website="https://www.programmerzamannow.com"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"